name: GRADIENT BLACK
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30547
title: GBK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bfbfbf'
    - '#404040'
    - '#000000'
    - '#5c5c5c'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
